### ISSUE TITLE
theme 구현

### ISSUE THREAD

**Issue by kouz95** [KTPT/surmoon-plz-server#11]

**Comment by kouz95** [comment]
api 주소가 `api/surveys/:id/themes`
보다 `api/themes`가 더 좋아보인다.

전자의 경우, survey에 속한 OneToMany일것 같다는 느낌이 든다. theme은 survey와 약한 연관 관계를 갖고 있는 Aggregate로 볼 수 있지 않을까.

survey의 id가 PathVariable로 들어오게 되면 유효성 검사하기가 영 불편하다.
만약 body로 들어온다면 `ConstraintValidator`를 사용하여 요청 오류를 dto에서 한번에 처리할 수 있을것 같다.

**Comment by kouz95** [comment]
survey가 처음 생성될때, 기본 theme을 생성시켜줘야할까?

**Comment by toneyparky** [comment]
[첫번째 코멘트](https://github.com/KTPT/surmoon-plz-server/issues/11#issuecomment-797872483)에 대해서 저도 후자의 경우가 더 시각적으로는 마음에 듭니다.

다만 이렇게 될 경우에는 [두번째 코멘트](https://github.com/KTPT/surmoon-plz-server/issues/11#issuecomment-797872552)와 연관된 의문이 생길거 같네요. theme을 하나의 aggregate로 본다면 생성주기가 survey와 달라질 텐데 기본 값을 넣어준다는게 같이 생성된다는 의미로 받아들여진다는 생각이 듭니다만 이 부분은 지식이 짧으니 의견을 물어보게씀니다🙂

추가적으로 삭제의 경우에도 theme만 삭제되어  theme이 없는 survey를 허락할 것인지(그 경우 기본 theme을 줄것인지) survey가 제거되면 theme도 제거되어야 하기에 제거주기(?)가 같다라 판단 되어야 하는지라는 생각도 드네요.

개념적인 부분이라 어려워 너무!! 그런데 너무 재미있어서 같이 이야기 나눠보면 좋을듯!

**Comment by Jummi10** [comment]
구글폼에서 제목 없는 설문지가 처음 새로 만들어질 때 테마 색상과 배경 색상, 기본 글꼴 스타일이 지정되어져서 만들어지는데 그럼 기본 theme이 있어야하지 않을까요??
존재하는 폼에서 테마 옵션이 없는 경우는 선택하지 못하는 것 같아요. 제 생각에는 설문지가 만들어질 때 theme도 동시에 생성이 되고 설문지가 삭제되면 테마도 같이 삭제되어야할거 같은데..설문지가 없는 theme이 삭제되지 않을 필요가 있느냐?에 대해서 없다고 생각이 되어서요
소프트웨어 공학 수업을 더 열심히 들어야겠네요! 좀이따 같이 이야기해봅시다!
